In [9]:
##넘파이 ndarray 개요

In [10]:
import numpy as np

In [11]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
#array1은 ndarray타입일 것이다. .shape는 ndarray의 형태를 보여준다.

array2 = np.array([[1,2,3],
                   [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)


array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

#array.shape의 결과에서, (1, 2) 이런 식이면, 튜플 안의 숫자 개수가 n개이면 n차원이라는 뜻이다.

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [12]:
print('array1: {}차원, array2: {}차원, array3: {}차원'.format(array1.ndim, array2.ndim, array3.ndim))
#array.ndim은 차원 수를 나타냄. 즉, 위의 array.shape에서 튜플 안 숫자 개수 n을 주는 것이다.

array1: 1차원, array2: 2차원, array3: 2차원


In [13]:
##ndarray의 데이터타입

In [14]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
#ndarray에서 데이터타입은 모두 같다.

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [15]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 =[1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
#데이터타입이 다를 경우에는 메모리가 더 큰 타입으로 모두 변환되어 저장된다.

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [16]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


##ndarray를 편리하게 생성하기 - arange, zeros, ones

In [17]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [18]:
sequence_array2 = np.arange(3, 19, 3)
print(sequence_array2)
#시작, 끝, 간격 순서로 인자가 들어간다. 끝-1 까지만 arange를 한다.

[ 3  6  9 12 15 18]


In [20]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((2,3))
print(one_array)
print(one_array.dtype, one_array.shape)
#dtype를 지정해주지 않으면 default값은 float64이다.

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1. 1.]
 [1. 1. 1.]]
float64 (2, 3)


##ndarray의 차원의 크기를 변경하는 reshape()

In [21]:
array1 = np.arange(0,24,2)
print('array1:\n', array1)

array2 = array1.reshape(3,4)
print('array2:\n', array2)

array3 = array2.reshape(2,3,2)
print('array3:\n', array3)

array1:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]
array2:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
array3:
 [[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


In [22]:
array1 = np.arange(24)
array2 = array1.reshape(-1, 6)
array3 = array2.reshape(4, -1, 3)

print('array1 shape: ', array1.shape, '\narray2 shape: ', array2.shape, '\narray3 shape:', array3.shape)
#reshape()는 -1을 활용하면 더욱 편리하다!

array1 shape:  (24,) 
array2 shape:  (4, 6) 
array3 shape: (4, 2, 3)


In [24]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원으로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원을 2차원으로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)
#reshape(-1,1)이 매우 자주 사용되는데, 이는 원본 ndarray와 관계없이 반드시 2차원이며 여러 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환해준다.

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


##넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

###단일 값 추출

In [26]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
value2 = array1[-3]
print('value:', value)
print('value2:', value2)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
value2: 7
<class 'numpy.int64'>


In [27]:
array1 = np.arange(10)

array1[0] = 1
array1[-2] = 4
print(array1)

[1 1 2 3 4 5 6 7 4 9]


In [28]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('row0,col0:', array2d[0,0])
print('row1,col2:', array2d[1,2])
print('row2,col0:', array2d[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
row0,col0: 1
row1,col2: 6
row2,col0: 8


###슬라이싱

In [29]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [47]:
array1 = np.arange(27)
array3d = array1.reshape(3,3,3)
print(array2, '\n\n')

array3 = array3d[:,:1, 1:3]
print(array3, '\n\n')

array4 = array3d[1:3, 0:2, 1:]
print(array4, '\n\n')

array5 = array3d[2:3, :, 2]
print(array5, '\n\n')

array6 = array3d[1:2, :, 0:2]
print(array6)

#[m:n]이면, 시작'인덱스'인 m부터 종료'인덱스' n-1까지 슬라이싱해온다.
#축에 있어서, 일부의 축에는 슬라이싱을, 일부의 축에는 인덱싱을 섞어서 쓰는 것도 가능하다.

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[[ 1  2]]

 [[10 11]]

 [[19 20]]] 


[[[10 11]
  [13 14]]

 [[19 20]
  [22 23]]] 


[[20 23 26]] 


[[[ 9 10]
  [12 13]
  [15 16]]]


###팬시 인덱싱

In [55]:
array1 = np.arange(27)
array3d = array1.reshape(3,3,3)
print(array3d, '\n\n')

array2 = array3d[[0,2], :, :]
print(array2, '\n\n')

array3 = array3d[1:3, [0,2], 0:3]
print(array3)
#팬시 인덱싱은, 선택한 index의 축값만을 가져올 수 있다. (축 선택은 1개만 가능한 듯?)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[[ 9 10 11]
  [15 16 17]]

 [[18 19 20]
  [24 25 26]]]


In [56]:
###불린 인덱싱