In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [37]:
from sklearn.model_selection import train_test_split

# 데이터를 DataFrame 형태로 불러 옵니다.
ml_data = pd.read_csv('transformed_data.csv', encoding='cp949')
ml_data = ml_data[:-3]

# 의미없는 변수는 삭제합니다.
ml_data = ml_data.drop(columns=['Season', 'HomeTeam', 'AwayTeam'])

X = ml_data.drop(columns=['Result'])
y = ml_data['Result'].astype('int32')
y = y.replace({3:2, 1:1, 0:0})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


# 학습용 데이터를 tf.data.Dataset 형태로 변환합니다. from_tensor_slices 함수를 사용하여 변환하고 batch를 수행하게 합니다.
train_ds = tf.data.Dataset.from_tensor_slices((X_train.values, y_train.values))
train_ds = train_ds.shuffle(len(X_train)).batch(batch_size=5)

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, input_dim=16),
    tf.keras.layers.Dense(5),
    tf.keras.layers.Dense(1)
    ])


# 학습용 데이터를 바탕으로 모델의 학습을 수행합니다.
# compile 메서드를 사용하여 최적화 모델 설정합니다. loss는 mean_squared_error, optimizer는 adam으로 설정합니다.
# fit 메서드를 사용하여 Dataset으로 변환된 학습용 데이터를 학습합니다. epochs는 100으로 설정합니다.
model.compile(loss='mean_squared_error', optimizer='adam')
history = model.fit(train_ds, epochs=30, verbose=2)


"""
1. evaluate 메서드를 사용하여 테스트용 데이터의 loss 값을 계산합니다.
"""
loss1 = model.evaluate(test_X, test_Y, verbose=0)
loss2, acc = model.evaluate(X_test, y_test)
"""
2. predict 메서드를 사용하여 테스트용 데이터의 예측값을 계산합니다.
"""
predictions = model.predict(X_test)

# 결과를 출력합니다.
print("테스트 데이터의 Loss 값: ", loss1)
print("테스트 데이터의 Accuracy 값: ", acc)

Epoch 1/30
1241/1241 - 2s - loss: 1.6329
Epoch 2/30
1241/1241 - 2s - loss: 0.7000
Epoch 3/30
1241/1241 - 1s - loss: 0.6821
Epoch 4/30
1241/1241 - 1s - loss: 0.6816
Epoch 5/30
1241/1241 - 2s - loss: 0.6809
Epoch 6/30
1241/1241 - 3s - loss: 0.6715
Epoch 7/30
1241/1241 - 3s - loss: 0.6708
Epoch 8/30
1241/1241 - 2s - loss: 0.6514
Epoch 9/30
1241/1241 - 1s - loss: 0.6516
Epoch 10/30
1241/1241 - 1s - loss: 0.6474
Epoch 11/30
1241/1241 - 2s - loss: 0.6439
Epoch 12/30
1241/1241 - 2s - loss: 0.6403
Epoch 13/30
1241/1241 - 2s - loss: 0.6367
Epoch 14/30
1241/1241 - 2s - loss: 0.6352
Epoch 15/30
1241/1241 - 1s - loss: 0.6343
Epoch 16/30
1241/1241 - 1s - loss: 0.6336
Epoch 17/30
1241/1241 - 1s - loss: 0.6299
Epoch 18/30
1241/1241 - 1s - loss: 0.6306
Epoch 19/30
1241/1241 - 2s - loss: 0.6312
Epoch 20/30
1241/1241 - 2s - loss: 0.6280
Epoch 21/30
1241/1241 - 2s - loss: 0.6275
Epoch 22/30
1241/1241 - 2s - loss: 0.6291
Epoch 23/30
1241/1241 - 1s - loss: 0.6271
Epoch 24/30
1241/1241 - 1s - loss: 0.6289
E

NameError: name 'test_X' is not defined

In [43]:
predictions = model.predict(X_test)

In [48]:
lst=[]
for x in predictions:
    lst.append(np.round(x, 1))

In [49]:
lst

[array([1.5], dtype=float32),
 array([1.3], dtype=float32),
 array([1.4], dtype=float32),
 array([1.], dtype=float32),
 array([1.1], dtype=float32),
 array([1.], dtype=float32),
 array([0.8], dtype=float32),
 array([1.5], dtype=float32),
 array([1.2], dtype=float32),
 array([1.6], dtype=float32),
 array([0.8], dtype=float32),
 array([1.3], dtype=float32),
 array([1.4], dtype=float32),
 array([1.1], dtype=float32),
 array([1.4], dtype=float32),
 array([1.5], dtype=float32),
 array([0.8], dtype=float32),
 array([1.1], dtype=float32),
 array([0.8], dtype=float32),
 array([0.9], dtype=float32),
 array([1.3], dtype=float32),
 array([1.7], dtype=float32),
 array([1.2], dtype=float32),
 array([1.3], dtype=float32),
 array([1.4], dtype=float32),
 array([0.9], dtype=float32),
 array([1.], dtype=float32),
 array([1.3], dtype=float32),
 array([0.8], dtype=float32),
 array([1.5], dtype=float32),
 array([1.2], dtype=float32),
 array([0.6], dtype=float32),
 array([1.2], dtype=float32),
 array([1.2],

In [6]:
ml_data = pd.read_csv('transformed_data.csv', encoding='cp949')

In [7]:
ml_data

Season        HomeTeam     AwayTeam  FTG  FTR  HTG  HTR     S    ST  \
0     2001-02        Charlton      Everton    0    3  1.0    5  -4.0   2.0   
1     2001-02           Derby    Blackburn   -8   -3  0.0    0 -16.0 -18.0   
2     2001-02           Leeds  Southampton    8    5  5.0    3  15.0  18.0   
3     2001-02       Leicester       Bolton   -1   -1 -2.0    2   7.0   7.0   
4     2001-02       Liverpool     West Ham    8   10  1.0    6   1.0   3.0   
...       ...             ...          ...  ...  ...  ...  ...   ...   ...   
7753  2021-22         Chelsea        Leeds    9    8  6.0   11  92.0  28.0   
7754  2021-22         Norwich   Man United   -5   -5 -2.0   -5 -23.0 -24.0   
7755  2021-22       Leicester    Newcastle    2    1  3.0    0   3.0 -11.0   
7756  2021-22         Burnley     West Ham   -6   -2 -3.0   -5 -19.0 -19.0   
7757  2021-22  Crystal Palace      Everton    0    0  2.0    2   4.0  -8.0   

         C     F     Y   Rn   R1  LSR  CSR  LHAP  LMP  LMHAP Result  
0      7.0 -26.0  -9.0 -1.0  0.0    7    0     4    0      3      0  
1     -8.0  -1.0  -3.0  1.0  0.0    4    0     1    0      0      3  
2     11.0   7.0   4.0  1.0  0.0    6    0    11    0      3      3  
3     -5.0  17.0   9.0  0.0  0.0    8    0     3    0      0      0  
4     -7.0  -9.0  -7.0  0.0  0.0   12    0     9    3      3      3  
...    ...   ...   ...  ...  ...  ...  ...   ...  ...    ...    ...  
7753  43.0  53.0  10.0  0.0  0.0    5   12     8    9     12      3  
7754 -13.0  -9.0   4.0  0.0  0.0  -19  -14    -8   -9     -9      0  
7755   5.0  12.0  -2.0 -2.0  0.0    7    8    -1    3     -3      N  
7756  -1.0 -20.0   0.0 -1.0  0.0  -11  -14     4    3      0      N  
7757   8.0  -8.0  -3.0  0.0  0.0   -4   -2     0   -6     -6      N  

[7758 rows x 20 columns]

In [65]:
from sklearn.model_selection import train_test_split

# 데이터를 DataFrame 형태로 불러 옵니다.
ml_data = pd.read_csv('transformed_data.csv', encoding='cp949')
ml_data = ml_data[:-3]

# 의미없는 변수는 삭제합니다.
ml_data = ml_data.drop(columns=['Season', 'HomeTeam', 'AwayTeam', 'LSR', 'CSR'])

X = ml_data.drop(columns=['Result'])
y = ml_data['Result'].astype('int32')
y = y.replace({3:2, 1:1, 0:0})

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


# 학습용 데이터를 tf.data.Dataset 형태로 변환합니다. from_tensor_slices 함수를 사용하여 변환하고 batch를 수행하게 합니다.
train_ds = tf.data.Dataset.from_tensor_slices((X_train.values, y_train.values))
train_ds = train_ds.shuffle(len(X_train)).batch(batch_size=5)

"""
1. keras를 활용하여 신경망 모델을 생성합니다.
   3가지 범주를 갖는 label 데이터를 분류하기 위해서 마지막 레이어 노드를 아래와 같이 설정합니다.
"""
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(9, input_dim=14),
    tf.keras.layers.Dense(8, activation='sigmoid'),
    tf.keras.layers.Dense(5, activation='sigmoid'),
    tf.keras.layers.Dense(3, activation='softmax')
    ])
#
# 학습용 데이터를 바탕으로 모델의 학습을 수행합니다.
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
history = model.fit(train_ds, epochs=30, verbose=2)

# 테스트용 데이터를 바탕으로 학습된 모델을 평가합니다.
loss, acc = model.evaluate(X_test, y_test)

# 테스트용 데이터의 예측값을 구합니다.
predictions = model.predict(X_test)

# 결과를 출력합니다.
print("테스트 데이터의 Accuracy 값: ", acc)
for i in range(5):
    print("%d 번째 테스트 데이터의 실제값: %d" % (i, y_test.iloc[i]))
    print("%d 번째 테스트 데이터의 예측값: %d" % (i, np.argmax(predictions[i])))

Epoch 1/30
1241/1241 - 2s - loss: 1.0482 - accuracy: 0.4778
Epoch 2/30
1241/1241 - 2s - loss: 1.0174 - accuracy: 0.5111
Epoch 3/30
1241/1241 - 2s - loss: 1.0122 - accuracy: 0.5108
Epoch 4/30
1241/1241 - 2s - loss: 1.0094 - accuracy: 0.5181
Epoch 5/30
1241/1241 - 2s - loss: 1.0087 - accuracy: 0.5187
Epoch 6/30
1241/1241 - 2s - loss: 1.0077 - accuracy: 0.5171
Epoch 7/30
1241/1241 - 2s - loss: 1.0063 - accuracy: 0.5189
Epoch 8/30
1241/1241 - 2s - loss: 1.0045 - accuracy: 0.5200
Epoch 9/30
1241/1241 - 3s - loss: 1.0052 - accuracy: 0.5201
Epoch 10/30
1241/1241 - 2s - loss: 1.0044 - accuracy: 0.5219
Epoch 11/30
1241/1241 - 3s - loss: 1.0040 - accuracy: 0.5187
Epoch 12/30
1241/1241 - 3s - loss: 1.0032 - accuracy: 0.5219
Epoch 13/30
1241/1241 - 3s - loss: 1.0032 - accuracy: 0.5214
Epoch 14/30
1241/1241 - 3s - loss: 1.0025 - accuracy: 0.5214
Epoch 15/30
1241/1241 - 3s - loss: 1.0022 - accuracy: 0.5198
Epoch 16/30
1241/1241 - 2s - loss: 1.0012 - accuracy: 0.5221
Epoch 17/30
1241/1241 - 2s - loss

In [66]:
predictions

array([[0.487038  , 0.23845166, 0.27451038],
       [0.4648001 , 0.23404612, 0.30115372],
       [0.13045204, 0.22311823, 0.6464297 ],
       ...,
       [0.16379875, 0.29337507, 0.5428261 ],
       [0.10349779, 0.2302868 , 0.6662155 ],
       [0.18275164, 0.24166791, 0.5755804 ]], dtype=float32)

In [67]:
lst = []
for i in range(1500):
    lst.append(np.argmax(predictions[i]))

In [68]:
pd.Series(lst).value_counts()

2    1036
0     464
dtype: int64