##넘파이 ndarray 개요

In [2]:
import numpy as np

In [3]:
array1 = np.array([1,2,3])
print('array1 type:', type(array1))
print('array1 array 형태:', array1.shape)
#array1은 ndarray타입일 것이다. .shape는 ndarray의 형태를 보여준다.

array2 = np.array([[1,2,3],
                   [4,5,6]])
print('array2 type:', type(array2))
print('array2 array 형태:', array2.shape)


array3 = np.array([[1,2,3]])
print('array3 type:', type(array3))
print('array3 array 형태:', array3.shape)

#array.shape의 결과에서, (1, 2) 이런 식이면, 튜플 안의 숫자 개수가 n개이면 n차원이라는 뜻이다.

array1 type: <class 'numpy.ndarray'>
array1 array 형태: (3,)
array2 type: <class 'numpy.ndarray'>
array2 array 형태: (2, 3)
array3 type: <class 'numpy.ndarray'>
array3 array 형태: (1, 3)


In [4]:
print('array1: {}차원, array2: {}차원, array3: {}차원'.format(array1.ndim, array2.ndim, array3.ndim))
#array.ndim은 차원 수를 나타냄. 즉, 위의 array.shape에서 튜플 안 숫자 개수 n을 주는 것이다.

array1: 1차원, array2: 2차원, array3: 2차원


##ndarray의 데이터타입

In [5]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
#ndarray에서 데이터타입은 모두 같다.

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


In [6]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 =[1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)
#데이터타입이 다를 경우에는 메모리가 더 큰 타입으로 모두 변환되어 저장된다.

['1' '2' 'test'] <U21
[1. 2. 3.] float64


In [7]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


##ndarray를 편리하게 생성하기 - arange, zeros, ones

In [8]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


In [9]:
sequence_array2 = np.arange(3, 19, 3)
print(sequence_array2)
#시작, 끝, 간격 순서로 인자가 들어간다. 끝-1 까지만 arange를 한다.

[ 3  6  9 12 15 18]


In [10]:
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((2,3))
print(one_array)
print(one_array.dtype, one_array.shape)
#dtype를 지정해주지 않으면 default값은 float64이다.

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1. 1.]
 [1. 1. 1.]]
float64 (2, 3)


##ndarray의 차원의 크기를 변경하는 reshape()

In [11]:
array1 = np.arange(0,24,2)
print('array1:\n', array1)

array2 = array1.reshape(3,4)
print('array2:\n', array2)

array3 = array2.reshape(2,3,2)
print('array3:\n', array3)

array1:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]
array2:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]
array3:
 [[[ 0  2]
  [ 4  6]
  [ 8 10]]

 [[12 14]
  [16 18]
  [20 22]]]


In [12]:
array1 = np.arange(24)
array2 = array1.reshape(-1, 6)
array3 = array2.reshape(4, -1, 3)

print('array1 shape: ', array1.shape, '\narray2 shape: ', array2.shape, '\narray3 shape:', array3.shape)
#reshape()는 -1을 활용하면 더욱 편리하다!

array1 shape:  (24,) 
array2 shape:  (4, 6) 
array3 shape: (4, 2, 3)


In [13]:
array1 = np.arange(8)
array3d = array1.reshape(2,2,2)
print('array3d:\n', array3d.tolist())

#3차원 ndarray를 2차원으로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

#1차원을 2차원으로 변환
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)
#reshape(-1,1)이 매우 자주 사용되는데, 이는 원본 ndarray와 관계없이 반드시 2차원이며 여러 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환해준다.

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


##넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

###단일 값 추출

In [14]:
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

value = array1[2]
value2 = array1[-3]
print('value:', value)
print('value2:', value2)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
value2: 7
<class 'numpy.int64'>


In [15]:
array1 = np.arange(10)

array1[0] = 1
array1[-2] = 4
print(array1)

[1 1 2 3 4 5 6 7 4 9]


In [16]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('row0,col0:', array2d[0,0])
print('row1,col2:', array2d[1,2])
print('row2,col0:', array2d[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
row0,col0: 1
row1,col2: 6
row2,col0: 8


###슬라이싱

In [17]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [18]:
array1 = np.arange(27)
array3d = array1.reshape(3,3,3)
print(array2, '\n\n')

array3 = array3d[:,:1, 1:3]
print(array3, '\n\n')

array4 = array3d[1:3, 0:2, 1:]
print(array4, '\n\n')

array5 = array3d[2:3, :, 2]
print(array5, '\n\n')

array6 = array3d[1:2, :, 0:2]
print(array6)

#[m:n]이면, 시작'인덱스'인 m부터 종료'인덱스' n-1까지 슬라이싱해온다.
#축에 있어서, 일부의 축에는 슬라이싱을, 일부의 축에는 인덱싱을 섞어서 쓰는 것도 가능하다.

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] 


[[[ 1  2]]

 [[10 11]]

 [[19 20]]] 


[[[10 11]
  [13 14]]

 [[19 20]
  [22 23]]] 


[[20 23 26]] 


[[[ 9 10]
  [12 13]
  [15 16]]]


###팬시 인덱싱

In [19]:
array1 = np.arange(27)
array3d = array1.reshape(3,3,3)
print(array3d, '\n\n')

array2 = array3d[[0,2], :, :]
print(array2, '\n\n')

array3 = array3d[1:3, [0,2], 0:3]
print(array3)
#팬시 인덱싱은, 선택한 index의 축값만을 가져올 수 있다. (축 선택은 1개만 가능한 듯?)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] 


[[[ 9 10 11]
  [15 16 17]]

 [[18 19 20]
  [24 25 26]]]


###불린 인덱싱

In [20]:
array1d = np.arange(start=1, stop=10)
#[]안에 array1d>5 Boolean indexing을 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [21]:
array1d>5
#이렇게 조건식만 붙여도, T와 F로 이루어진 ndarray 객체를 반환해준다.

array([False, False, False, False, False,  True,  True,  True,  True])

In [22]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [23]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


##행렬의 정렬 - sort()와 argsort()

###행렬 정렬

In [24]:
org_array = np.array([3, 1, 9, 5])
print('원본 행렬:', org_array)
#np.sort()로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort() 호출 후 원본 행렬:', org_array)
#ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort() 호출 후 원본 행렬:', org_array)

#쉽게 생각해서, sorted() 함수가 np.sort() 함수의 역할이며, .sort() 메쏘드는 그대로라 생각하자!

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬: [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬: None
org_array.sort() 호출 후 원본 행렬: [1 3 5 9]


In [25]:
sort_array1_desc = np.sort(org_array)[::-1]  #[::-1] 쓰면 내림차순 정렬된다!
print('내림차순으로 정렬:', sort_array1_desc)

내림차순으로 정렬: [9 5 3 1]


In [26]:
array2d = np.array([[8,12],
                    [7,1]])
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('로우 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('칼럼 방향으로 정렬: \n', sort_array2d_axis1)

로우 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


###정렬된 행렬의 인덱스를 반환하기

In [28]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)
print(org_array) #.argsort() 메쏘드는 원본 행렬에 영향이 없다.

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]
[3 1 9 5]


In [29]:
org_array = np.array([3, 1, 9, 5])
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


In [30]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


##선형대수 연산 - 행렬 내적과 전치 행렬 구하기

###행렬 내적(행렬 곱)

In [32]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])
B = np.array( [[7, 8],
              [9, 10],
              [11, 12]])
dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [33]:
A = np.array([[1, 2,],
             [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
